- name: Get bazel
  get_url:
    url: https://github.com/bazelbuild/bazel/releases/download/0.16.1/bazel-0.16.1-installer-linux-x86_64.sh
    dest: /tmp/bazel.sh
    checksum: sha256:17ab70344645359fd4178002f367885e9019ae7507c9c1ade8220f3628383444

- name: Make bazel executable
  file: path=/tmp/bazel.sh mode="u+x"

- name: Install bazel
  command: bash bazel.sh
  args:
    chdir: /tmp
    creates: /usr/local/bin/bazel

