- name: Install packages 
  apt: name={{item}}
  with_items:
    - maven
    - xubuntu-desktop
    - openjdk-8-jdk
    - pkg-config
    - zip
    - g++
    - zlib1g-dev
    - unzip
    - python
    - tigervnc-standalone-server
    - tigervnc-xorg-extension
    - tigervnc-viewer
